services:
  node:
    image: ghcr.io/gribkovartem/movie-db
    build:
      context: .
      dockerfile: ./Dockerfile.node
    ports:
      - '3000:3000'
  proxy:
    image: ghcr.io/gribkovartem/movie-db-proxy
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - node
    ports:
      - '80:8000'
    restart: always
