FROM node:18-alpine

WORKDIR /app

COPY . .

RUN npm ci
RUN npm run build:client

COPY ./public ./public

FROM nginx:1.27-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=0 /app/public /usr/share/nginx/html

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]